SOCIAL_AUTH_TWITTER_KEY = "oIxGjMvP6ij1FonUnvWWXjAsI"
SOCIAL_AUTH_TWITTER_SECRET = "BmdHs1ROdutUGZrGE8HlEVCTVnp9r549gjJjZXKGyqWwddJnIy"

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'